### ISSUE TITLE
Standard output truncated when writing to /dev/stderr

### ISSUE THREAD

**Issue by rudymatela** [aureliojargas/clitest#27] opened 2018-04-04 16:40 UTC
Consider the following three files:

1. `ok.sh`

```bash
#!/bin/bash
echo 'stdout'
echo 'stderr' >&2
```

2. `not-ok.sh`

```bash
#!/bin/sh
echo 'stdout' > /dev/stdout
echo 'stderr' > /dev/stderr
```

3. `example.txt`

```bash
$ sh ok.sh
stdout
stderr
$ sh not-ok.sh
stdout
stderr
```

I get the following output from `clitest example.txt`:

```bash
$ clitest example.txt 
#1	sh ok.sh
#2	sh not-ok.sh
-----------------------------------------------------------------------------
[FAILED #2, line 4] sh not-ok.sh
@@ -1,2 +1 @@
-stdout
 stderr
-----------------------------------------------------------------------------

FAIL: 1 of 2 tests failed
```

Somehow, the standard output gets truncated on the `not-ok.sh` script.  Note the following:
```bash
$ sh not-ok.sh > out 2> err 
$ cat out
stdout
$ cat err
stderr
```

Is this a bug in clitest?  Or am I doing something that I should not be doing?

The following script triggers the same behaviour in `clitest` (standard output is still truncated):

* `also-not-ok.sh`

```bash
#!/bin/sh
echo 'stdout'
echo 'stderr' > /dev/stderr
```

**Comment by rudymatela** [comment] 2018-04-04 16:43
This problem is not exclusive to shell scripts.  Consider the following three files:

1. `ok.c`

```c
#include <stdio.h>
int main()
{
	fprintf(stdout, "stdout\n");
	fprintf(stderr, "stderr\n");
	return 0;
}
```

2. `not-ok.c`

```c
#include <stdio.h>
int main()
{
	FILE *out = fopen("/dev/stdout","w");
	FILE *err = fopen("/dev/stderr","w");
	if (out == NULL || err == NULL)
		return 1;
	fprintf(out, "stdout\n");
	fprintf(err, "stderr\n");
	fclose(out);
	fclose(err);
	return 0;
}
```

3. `c-example.txt`

```bash
$ cc ok.c -o ok && ./ok
stderr
stdout
$ cc not-ok.c -o not-ok && ./not-ok
stderr
stdout
```

`clitest` still truncates stdout when writing to `/dev/stderr`:

```bash
$ clitest c-example.txt 
#1	cc ok.c -o ok && ./ok
#2	cc not-ok.c -o not-ok && ./not-ok
-----------------------------------------------------------------------------
[FAILED #2, line 4] cc not-ok.c -o not-ok && ./not-ok
@@ -1,2 +1 @@
 stderr
-stdout
-----------------------------------------------------------------------------

FAIL: 1 of 2 tests failed
```

**Comment by aureliojargas** [comment] 2018-04-06 17:03
Thanks for the report.

I confirm this error in:

- Debian 6.0.10, dash 0.5.5.1
- Ubuntu 14.04.5, bash 4.3.11
- Ubuntu 16.04, bash 4.3.48
- Alpine, `/bin/sh` is busybox (running inside Docker)

But... It works as expected in OS X 10.11.6, bash 3.2.57 

```console
$ bash ../github/aureliojargas/clitest/clitest example.txt 
#1	sh ok.sh
#2	sh not-ok.sh
OK: 2 of 2 tests passed
$ dash ../github/aureliojargas/clitest/clitest example.txt 
#1	sh ok.sh
#2	sh not-ok.sh
OK: 2 of 2 tests passed
$ /bin/sh ../github/aureliojargas/clitest/clitest example.txt 
#1	sh ok.sh
#2	sh not-ok.sh
OK: 2 of 2 tests passed
$
```

🤔

**Comment by aureliojargas** [comment] 2018-04-06 19:31
Let's put clitest aside and test just plain bash commands.

The script works with no redirection:

```console
$ cat bug.sh 
echo stdout > /dev/stdout
echo stderr > /dev/stderr
$ bash bug.sh  
stdout
stderr
$
```

It works when redirecting only STDOUT or STDERR:

```console
$ bash bug.sh > foo
stderr
$ cat foo
stdout
$ bash bug.sh 2> foo
stdout
$ cat foo
stderr
$
```

But it discards STDOUT when redirecting both:

```console
$ bash bug.sh > foo 2> foo
$ cat foo
stderr
$ bash bug.sh > foo 2>&1  
$ cat foo
stderr
$ bash bug.sh 2> foo > foo
$ cat foo
stderr
$ bash bug.sh 2> foo >&2
$ cat foo
stderr
$ bash bug.sh &> foo
$ cat foo
stderr
$ 
```

In OS X, all those commands work as expected.

I don't know what is happening here. At least it's not a clitest bug after all :)

**Comment by aureliojargas** [comment] 2020-07-01 21:17
Since the weird behavior described in this issue happens on the bash level, and varies among different operating systems, unfortunately there's nothing clitest can do about it. I'm closing this.

**Closed by aureliojargas** 2020-07-01 21:17 UTC

**Comment by vmmello** [comment] 2020-07-01 22:42
This quite an interesting problem.

```bash
#!/bin/sh
echo 'stdout'
echo 'stderr' > /dev/stderr
```

The above works on terminal (what is being referred on this issue as "without redirection") because there's no escape sequence to reset the terminal position, so the output is shown sequentially as expected.

When you redirect it to a file (that is how `clitest` runs it) you have the 2 `echo` commands opening and writing to the same regular file, completely overwriting what was written in the previous open (i.e. every time `>` redirection is used without the ampersand (`&`) following with a file descriptor it completely overwrites the file, voiding the previous writes. Also testing as `$ bash bug.sh > foo 2> foo` is wrong for this same reason).

When executing the command, `clitest` does the right thing of duplicating `stdout` with `2>&1` what opens `stderr` duplicating `stdout` file descriptor (not ovewriting it):

```bash
253 tt_run_test() {
    ...
301    # Execute the test command, saving output (STDOUT and STDERR)
302    eval "$tt_test_command" > "$tt_test_output_file" 2>&1
    ...
431 }
```

So this is not a bug with `clitest`.

My conclusion is that writing to `>/dev/stderr` and `>/dev/stdout` is unnecessary and gross (...and well punished :yum:).

**Comment by aureliojargas** [comment] 2020-07-02 06:20
Thank you very much @vmmello for your detailed explanation :+1: 

It's still puzzling to me how even the "wrong" commands work in macOS. Anyway, as you've said, it's not common to redirect like that, so I guess it's ok to just avoid it :)
